version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - setup_remote_docker
      # Mavenキャッシュ
      - restore_cache:
          keys:
            - maven-{{checksum "pom.xml"}}
            - maven
      - run:
          name: build and push to GitHub Packages
          command: |
            docker login ghcr.io -u ${GITHUB_USER} -p ${GITHUB_TOKEN}
            mvn -X -B package docker:build docker:push -Dimage.tag=`date +%Y%m%dT%H%M%S-%3N` --file pom.xml -s ./.circleci/settings.xml
      - save_cache:
          paths:
            - ~/.m2
          key: 
            maven-{{checksum "pom.xml"}}
          expire: 1d
